name: Zotero Android CI

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs once a week (Sunday at midnight)
  workflow_dispatch:
  
jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Upstream Repository
        run: |
          git remote add upstream https://github.com/zotero/zotero-android.git
          git fetch upstream
          git checkout master

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Merge Changes from Upstream
        run: |
          git merge --allow-unrelated-histories -X theirs upstream/master
          git reset .github/
          
      # Push merged changes to fork
      - name: Push Changes to Fork
        run: |
          git push origin master

  build:
    runs-on: ubuntu-latest
    needs: sync-upstream
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Grant execute permission for bundle_translators.py
        run: chmod +x scripts/bundle_translators.py

      - name: Execute bundle_translators.py
        run: python3 scripts/bundle_translators.py

      - name: Grant execute permission for bundle_translation.py
        run: chmod +x scripts/bundle_translation.py

      - name: Execute bundle_translation.py
        run: python3 scripts/bundle_translation.py

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Skip downloading dependencies from remote repositories to avoid authentication
      - name: Build the app without remote credentials
        run: ./gradlew assembleDebug --no-configuration-cache -PpreDexLibs=false --stacktrace

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: nightly-tag-${{ steps.date.outputs.date }}
          name: nightly-release-${{ steps.date.outputs.date }}
          body: Built automatically from https://github.com/zotero/zotero-android
          artifacts: app/build/outputs/apk/debug/app-debug.apk
